### PR TITLE
fix: LANGUAGE_COOKIE_NAME is not set by default

### PR DESCRIPTION
**Pull request by cmltaWt0**
Regression caused by https://github.com/edx/edx-platform/pull/28796

Details:

```
response.delete_cookie(
    settings.LANGUAGE_COOKIE_NAME,
    domain=settings.SHARED_COOKIE_DOMAIN
)
caused an Exception due to absence of LANGUAGE_COOKIE_NAME settings variable

> production.py

LANGUAGE_COOKIE_NAME = ENV_TOKENS.get('LANGUAGE_COOKIE', None) or ENV_TOKENS.get('LANGUAGE_COOKIE_NAME')
```

Exception:

```python
2021-10-07 20:26:57,299 INFO 8 [audit] [user 3] [ip 172.19.0.1] models.py:2723 - Login success - user.id: 3
2021-10-07 20:26:57,318 INFO 8 [openedx_events.tooling] [user 3] [ip 172.19.0.1] tooling.py:160 - Responses of the Open edX Event <org.openedx.learning.auth.session.login.completed.v1>:
[]
2021-10-07 20:26:57,429 ERROR 8 [root] [user 3] [ip 172.19.0.1] signals.py:22 - Uncaught exception from None
Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "./openedx/core/djangoapps/lang_pref/middleware.py", line 93, in process_response
    response.delete_cookie(
  File "/openedx/venv/lib/python3.8/site-packages/django/http/response.py", line 216, in delete_cookie
    secure = key.startswith(('__Secure-', '__Host-'))
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### CODE REVIEW

**Comment by cmltaWt0** [comment]
> Thanks for your PR @cmltaWt0! I understand that you are trying to address a misconfiguration of the edx-platform production settings. Indeed, in the production settings of edx-platform, we currently have ([source](https://github.com/edx/edx-platform/blob/9ef8332a60df83ffdf20d7e718ab4f1f2c0ec69c/lms/envs/production.py#L297)):
> 
> ```
> LANGUAGE_COOKIE_NAME = ENV_TOKENS.get('LANGUAGE_COOKIE', None) or ENV_TOKENS.get('LANGUAGE_COOKIE_NAME')
> ```
> 
> This is all the more unfortunate that the common settings provide a good default value for this setting ([source](https://github.com/edx/edx-platform/blob/9ef8332a60df83ffdf20d7e718ab4f1f2c0ec69c/lms/envs/common.py#L1713)):
> 
> ```
> LANGUAGE_COOKIE_NAME = "openedx-language-preference"
> ```
> 
> So I think it would be better if the edx-platform settings could be fixed upstream:
> 
> ```
> LANGUAGE_COOKIE_NAME = ENV_TOKENS.get('LANGUAGE_COOKIE') or ENV_TOKENS.get('LANGUAGE_COOKIE_NAME', LANGUAGE_COOKIE_NAME)
> ```
> 
> I understand that it might be easier to get a PR merged in the Tutor nightly branch than in edx-platform. So what I suggest is that you open a PR on the edx-platform repo; if it cannot be immediately merged, get back here and we'll merge this one. Once your PR is merged in edx-platform, revert your change in the Tutor nightly branch.
> 
> What do you think?

Thanks a lot in such a good analysis. I was thinking the same way and didn't want to add any line of code to the tutor codebase but fix it in upstream.

Will create a PR to the edx-platform and let's hope it will be merged quickly. Simultaneously will changes this PR (to have plan B) based on the best practices you mentioned.
